### ISSUE TITLE
Cannot find  global_tracker.xml for analytics sample

### ISSUE THREAD

**Issue by fuyun** [googlesamples/google-services#26]
I have to create a dummy one to make it build.

**Comment by silvolu** [comment]
It should just work if you follow the [quickstart setup guide](https://developers.google.com/analytics/devguides/collection/android/v4/start), please re-open if that's not the case.
We had the wrong link in the README, I fixed it in decfed493f9092c7dcb3b4e66a51365a298020a3, sorry about that!

**Comment by fuyun** [comment]
I followed the guide. It could not be built with error message on missing global_tracker.xml for 

      mTracker = analytics.newTracker(R.xml.global_tracker);

I copied a global_tracker.xml to res/xml to make it build. But it still won't work. I am wondering if we should provide global_tracker here. Obviously newTracker does not understand global_tracker.xml, it needs tracker definition.

**Comment by silvolu** [comment]
Sorry, I thought you were referring to the iOS guide!

**Comment by fuyun** [comment]
hmm, is that because I changed the following versions in build.gradle:

        classpath 'com.android.tools.build:gradle:1.2.3'

    compileSdkVersion 21
    buildToolsVersion "21.1.2"

**Comment by fuyun** [comment]
I copied a global tracker xml from https://developers.google.com/analytics/devguides/collection/android/v4/#tracking-methods

I saw error messages

07-16 13:37:59.581  16033-16033/com.google.samples.quickstart.analytics W/GAV4﹕ Thread[main,5,main]: int configuration name not recognized:  ga_dispatchPeriod
07-16 13:37:59.581  16033-16033/com.google.samples.quickstart.analytics W/GAV4﹕ Thread[main,5,main]: bool configuration name not recognized:  ga_dryRun

it does not work until I added ga_trackingId and ga_autoActivityTracking

**Comment by silvolu** [comment]
Apologies for the delay in replying! The gradle version change should not be a problem, and the resource should be added by the google-services plugin.
Does the package name in the google-services.json configuration file match the package name you are using when building the sample?

**Comment by fuyun** [comment]
Actually when I created a project from scratch, it works. An global tracker xml can be automatically created from google-services.json. But the example does not work for me. I did not follow and don't know why.

**Comment by silvolu** [comment]
I think the reason was a mismatch between the package name in the google-services.json configuration file and the package name you were using in the code.

**Comment by Sottti** [comment]
It's confusing!!

In the documentation says this:
tracker = analytics.newTracker("UA-XXXXX-Y"); // Replace with actual tracker/property Id

The code example uses:
mTracker = analytics.newTracker(R.xml.global_tracker);

The doce example doesn't even have that xml file and the documentation file doesn't include the tracking ID!! Crazy.

<?xml version="1.0" encoding="utf-8" ?>
<resources>
  
  <string name="ga_appName">My App</string>

  
  <string name="ga_appVersion">1.0</string>

  
  <integer name="ga_dispatchPeriod">1800</integer>

  
  <bool name="ga_dryRun">false</bool>
</resources>

**Comment by silvolu** [comment]
@Sottti this example is about how to use Analytics with the configuration flow enabled at https://developers.google.com/mobile/add and the google services gradle plugin (that will give you the xml file).

The docs at https://developers.google.com/analytics/devguides/collection/android/v4/#tracking-methods discuss how to configure the tracker without using the new flow and the plugin, hence the tracker id is explicitly passed as a string.

I'm sorry if you find it confusing, let us know if you have any suggestions on how to make it more clear!

**Comment by HakAl** [comment]
The sample app in google-services > android > analytics (https://github.com/googlesamples/google-services/tree/master/android/analytics) won't even compile because there is no R.xml.global_tracker file. I appreciate all the help, but there's a wide variety of info provided by Google, about Analytics. Much of that information is conflicting and the provided samples are outdated and won't even compile. 

Suggestions? A single source of truth from Google, with clearly archived version documentation. Updated samples that actually compile!

**Comment by akbarsha03** [comment]
I pass only the PROPERTY_ID instead of R.xml.global_tracker and kept the json file in the root directory of the module and All the required screen names are done in coding using the HitBuilders

**Comment by ryandh** [comment]
yes, I got the same thing. have to replace the resourceid with the analytics id, like UA-XXXXXX

**Comment by NishaMore** [comment]
Hi,

I am also facing the same issue. Did anyone solved it? Please tell me the solution. I have tried to replace global_tracker with property id but nothing works!

Thanks.

**Comment by akbarsha03** [comment]
Make sure you've the json file on the root of the module and pass the Property ID not the global_tracker.xml @NishaMore

**Comment by lutaseb** [comment]
seriously I agree with all the comments writtent above, 
- download the sample and run it -> doesn't compile doesn't work
- try to download the json and put it in the app directory...build... doesn't find this R.xml.global_tracker (we don't even know where it comes from since it is not explained...guess it should be generated...but who knows)
I really think I way that works should be more than enough

**Comment by beetree** [comment]
Could someone please provide a workaround? The XML file doesn't generate even if I have google-services.json in app/. And, yes, I've double checked the package_name.

Would the workaround below work?

http://stackoverflow.com/questions/32078992/error-cannot-find-symbol-variable-xml-while-trying-google-analytics

**Comment by beetree** [comment]
Okay, so Build->"Clean Project" solved it for me. There seems to be some conflicts between the play-services-analytics and play-services that is resolved if you clean the project.

To be honest, I don't really understand what is going on in all these gradle files. So confusing...

**Comment by beetree** [comment]
Confirmed. It solved it. After that you'll get another error, that is resolved like this:

Fix error for "CampaignTrackingReceiver is not registered":
http://stackoverflow.com/questions/30429530/campaigntrackingreceiver-is-not-registered-google-analytics-v4

**Comment by vananden** [comment]
Found this because also perplexed. Easiest fix is to add a comment to the web page mentioning that you need to replace the "R.xml.global_tracker" with your assigned analytics id.

**Comment by odbol** [comment]
Ok, I had the same issue. This "new flow" thing is really complicated and has so many problems. Wish I had known you could just paste in the "UA" id to begin with; it would have saved me several hours of frustration.

The problem is:

1. The "Get Configuration File" step in the docs asks you for your Application package name. (e.g. "com.example.exampleapp")
2. I'm not adding the GA libs to my top-level package, I'm adding them to a module in the app that has a different package name than my app (e.g. "com.example.shared"). (duh, because it's a module).
3. Apparently the GA "new flow" is assuming all these package names and module names will be the same. Which for any serious app, they won't be.

Please add to the docs that you can just pass in your analytics ID into .newTracker(), instead of dealing with all this JSON file downloading and XML file generating malarky.

**Comment by samtstern** [comment]
@odbol thanks for the feedback.  We are going to publish a short official docs page explaining how the plugin works and the workarounds if you get into trouble now that we have learned the pain points from this thread and others like it.

Going to close this issue for now since the solution(s) are above.

**Comment by ferrannp** [comment]
Hi, so I understand that the ```google-services.json``` generates a ```global_tracker.xml```inside ```app/build/generated/res/google-services/debug/xml/```and it looks like:

```
<?xml version="1.0" encoding="utf-8"?>
<resources>
    <string name="ga_trackingId" translatable="false">UA-XXXXXXXX-X</string>
</resources>
```

I think this is good because then I can add my ```google-services.json``` into my ```.gitignore```and I can push my code without the ```ga_trackingId```. But then, how can I use my own xml file with extra configuration like shown in: https://developers.google.com/analytics/devguides/collection/android/v4/parameters ?

Is there a way I could merge the generated xml file ```global_tracker.xml``` with my ```res/xml/app_tracker.xml```file to create the tracker?

I know I can set up all the other configuration by code but I would like to still be able to use ```ga_autoActivityTracking```and set my ```screenNames``` in my xml.

**Comment by samtstern** [comment]
@ferrannp what happens if you leave `ga_trackingId` out of your checked-in configuration file, does this create an error?

I have reached out to the Analytics team, I will try to get an official answer here and update the documentation if necessayr.

**Comment by ferrannp** [comment]
@samtstern No, it does not create an error. 

I just think it would be nice to have a way to generate it (and I thought ```google-services.json```would do that for us). The same way you do for your .keystore or a .properties file saving api keys (which then you can read using gradle). Checking the xml file without ```ga_trackingId```, then add it again and remember not to push your xml file (ever) with the ```ga_trackingId``` is not really reliable.

**Comment by samtstern** [comment]
@ferrannp I've been discussing this with the analytics team as well as the engineer who maintains the `google-services` plugin.  This is great feedback and we want to find a way to make this work.

Also you may be interested in this guide we just published today which details exactly what the google-services plugin does.  This may help you going forward:
https://developers.google.com/android/guides/google-services-plugin

**Comment by samtstern** [comment]
I am going to close this issue since the original issue title is no longer relevant and at this point it could be a little while before we figure out a strategy to integrate those other Analytics XML properties.  I will ping this thread if/when we reach a solution. Thanks again for your feedback!

**Comment by ferrannp** [comment]
@samtstern thanks for your answer and for the link. At the end, I've just created an xml file that contains my ```ga_trackingId``` as a string resource (this file is added to my .gitignore). And then, in my app_tracker.xml, I can add that ```ga_trackingId``` using ```@string/secret_gaTrackingId```. So basically, I think, that covers what I was asking here :)

**Comment by norman784** [comment]
I've faced the same issue, to solve it just clean up the project and rebuild it, the reference to R.xml.global_tracker should be working by now

**Comment by IgorGanapolsky** [comment]
I don't understand.  I am facing the same issue.  I followed analytics setup instructions at https://developers.google.com/analytics/devguides/collection/android/v4/.  Why can't google provide solid instructions???

**Comment by freerider7777** [comment]
Hello!
I'm implementing analytics. Sample app compiles, ok. But I have one question - what is this all infrastracture with plugins and autogeneration for? :) For just single id! Why not just call single method like in AppFlyer AppsFlyerLib.setAppsFlyerKey("...."); ... Very strange...

**Comment by Ajit121** [comment]
just clean project. worked for me

**Comment by linuxjet** [comment]
I was looking at the same issue.  Then I noticed(at least in android studio) that the IDE generated app_tracker.xml instead of global_tacker.xml

**Comment by cooperkong** [comment]
just clean, you will get global_tracker.xml

**Comment by stoichoandreev** [comment]
linuxjet Ithink your are right

**Comment by twigbranch** [comment]
We also did not get a global_tracker.xml. Only an app_tracker.xml.

**Comment by azizimusa** [comment]
do this

`mTracker = analytics.newTracker("UA-xxxxxxx-1");`

solve ur problem

**Comment by rayluc25** [comment]
Where can I find the analytics ID in the form UA-xxxxxx-1?  Cleaning/Rebuilding project still doesn't fix the error of the missing R.xml.global_tracker

**Comment by azizimusa** [comment]
open GA website to get your own "UA-xxxxxxx-1". Then at this line 

mTracker = analytics.newTracker(R.xml.global_tracker);

replace with

mTracker = analytics.newTracker("UA-xxxxxxx-1");

**Comment by abiemann** [comment]
there's no XML file generated even though I've followed **Set up your project** exactly (except the library version is 9.4.0 now instead of 9.2.0).

I see that `newTracker()` should just be passed the UA ID, however, why?? You've got that lovely JSON file sitting in /app right now... is it not used? Can I delete the JSON file ?

I've rated the documentation one star : https://developers.google.com/analytics/devguides/collection/android/v4/

**Comment by danielsalzer42** [comment]
I have to admit, I have a hard time understanding the purpose of all this: 
- first you have to export the google-services.xml file. If you pick the wrong Goggle Analytics account or property you are stuck with it and you have to edit the exported file manually. 
**What's missing:** How do I change the selected values after I enabled the Google Analytics? 
- then you have to place the file into the root folder of your app. In my case, I had to edit the tracker id in the file manually
- then I tried to access R.xml.global_tracker. This did not work. The documentation describes that there are to xml files with string values generated that contain the tracking id. 
What's missing:  why are there 2 files? And If I want to access a single value, why would I not access the value with R.string.ga_trackingId? 
- in the end, I left my tracking id in the analytics.xml where I had it before.

**Comment by idish** [comment]
Given that the google-services.json generates the global_tracker xml file, I can't add my custom 
properties to that file such as `ga_reportUncaughtExceptions` to `true`.
I don't understand this.. The tutorial for setting the analytics totally contradicts itself as I cannot add anything to the generated(!!) xml file.
This is so frustrating seriously..

**Comment by s1155030742** [comment]
This question is raised in 2015 ,

In late 2016 I am here to find where the xml is. :(

**Comment by Imany-apk** [comment]
I have a Firebase App and I want to add GA to that.
if I **connect Firebase app to Google Analytics**, that will showing FA data or GA data ? 
because the view is just like FA
and in this case would be needed any "tracking_id" or gradle dependency ?

**Comment by hendrawd** [comment]
I updated android studio to 2.3 and this error comes up where previously fine

**Comment by fiskurgit** [comment]
Following this guide, error still occurs: https://developers.google.com/analytics/devguides/collection/android/v4/

**Comment by deltaguita** [comment]
I have the same issue, `clean project` can't fix it 😓

**Comment by akbarsha03** [comment]
This should no longer be an issue. As the inbuilt firebase assistant of the android studio helps you integrate google services

**Comment by deltaguita** [comment]
@akbarsha03 
How can I add both GA and firebase to my project by json file?

**Comment by deltaguita** [comment]
This answer work for me because I have both GA and firebase project.
http://stackoverflow.com/questions/37715288/is-it-possible-to-use-firebase-messaging-with-google-analytics-in-android?answertab=active#tab-top

**Comment by darrinps** [comment]
If Android Studio isn't recognizing the fact that the global_tracker.xml exists, then look at your imports and see if there is an android.R being pulled in. Delete that and it should then pick yours up.

**Comment by psnehanshu** [comment]
This [comment](https://groups.google.com/g/firebase-talk/c/bamCgTDajkw) suggests that `google-services.json` is safe to be checked into a Git repo as those values can be extracted from the APK anyway.
